# Alembic 配置文件
# 通过 env.py 中的代码读取数据库连接

[alembic]
# 迁移脚本存放目录
script_location = alembic

# 日志输出
sqlalchemy.url = mysql+pymysql://root:Cainiao%40123@localhost:3306/cainiao_design

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
